# Generated by Django 2.1.7 on 2019-03-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapleDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MapleName', models.CharField(max_length=50)),
                ('ServerIconURL', models.CharField(max_length=500)),
                ('GuildName', models.CharField(max_length=50)),
                ('MapleLevel', models.CharField(max_length=5)),
                ('MapleJob', models.CharField(max_length=50)),
                ('MapleServer', models.CharField(max_length=20)),
                ('MapleEXP', models.CharField(max_length=100)),
                ('MaplePopular', models.CharField(max_length=10)),
                ('MapleCharIMG_URL', models.CharField(max_length=500)),
                ('TotalRank', models.CharField(max_length=50)),
                ('WorldRank', models.CharField(max_length=50)),
                ('JobRank', models.CharField(max_length=50)),
                ('PopularRank', models.CharField(max_length=50)),
                ('UnionRank', models.CharField(max_length=50)),
                ('AchievementsRank', models.CharField(max_length=50)),
            ],
        ),
    ]
