# Generated by Django 2.1.7 on 2019-03-24 14:47

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Khan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mapledb',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='mapledb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
